# Generated by Django 3.2.9 on 2021-11-18 21:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadsign',
            name='sign_url',
        ),
        migrations.AddField(
            model_name='roadsign',
            name='photo',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to=''),
        ),
    ]
