# Generated by Django 3.2.9 on 2021-11-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessapp', '0002_auto_20211118_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadsign',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
