# Generated by Django 3.2.9 on 2021-11-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessapp', '0003_alter_roadsign_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadsign',
            name='photo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
